### ISSUE TITLE
Munitions Tech don't have access to viewscreens

### ISSUE THREAD

**Issue by deadmomo69** [DDMers/NSV13#143] opened 2019-11-23 19:08 UTC
## Reproduction:
Click on viewscreen on the wall as a munitions tech, you can use it but it gives a buzz saying access denied, and puts 
![image](https://user-images.githubusercontent.com/37983463/69483861-a043bb80-0dfa-11ea-8380-73df8cb12b55.png)
a camera button each time on your screen.

**Comment by gryffinp** [comment] 2019-11-23 19:13
I can confirm the same experience as a munitions tech.

**Comment by TheChosenEvilOne** [comment] 2019-11-23 20:08
The extra camera buttons are caused by the same problem as #145

**Comment by francinum** [comment] 2019-11-23 23:27
They have a req_access of `BRIDGE`

**Comment by francinum** [comment] 2019-12-29 22:49
Fixed in #160

**Closed by francinum** 2019-12-29 22:49 UTC
